apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Saurabh-dev-create/flask-argo.git'
    targetRevision: HEAD
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: flask-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



