apiVersion: v1
kind: Service
metadata:
  name: flask-argo-svc
  namespace: flask-demo
spec:
  type: ClusterIP
  selector:
    app: flask-argo-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  